# Generated by Django 4.2.7 on 2023-12-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipe_app.recipe'),
            preserve_default=False,
        ),
    ]
